version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
      timezone: "Europe/Vienna"

  - package-ecosystem: "pip"
    directory: "/"
    groups:
      python-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "Europe/Vienna"
