version: 2

formats:
  - pdf
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # Skip docs build if the commit message contains "skip ci"
    - (git --no-pager log --pretty="tformat:%s -- %b" -1 | grep -viq "skip ci") || exit 183
    # Skip docs build if there are no changes related to docs
    - |
      if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml src/mqt/ src/python include/*/python .github/contributing* .github/support*;
      then
        exit 183;
      fi
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
    - uv pip install .[docs] readthedocs-sphinx-ext
    - .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
    - |
      if [ "$READTHEDOCS_VERSION_TYPE" = "external" ];
      then
          .venv/bin/python -m sphinx -T -b singlehtml -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/htmlzip
      fi
    - |
      if [ "$READTHEDOCS_VERSION_TYPE" = "external" ];
      then
          .venv/bin/python -m sphinx -T -b latex -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/pdf
      fi
    - |
      if [ "$READTHEDOCS_VERSION_TYPE" = "external" ];
      then
          cd $READTHEDOCS_OUTPUT/pdf/ && latexmk -pdf -f -dvi- -ps- -interaction=nonstopmode
      fi

sphinx:
  configuration: docs/conf.py
