name: 🐍 • Minimums
on:
  workflow_call:
    secrets:
      token:
        description: "The token to use for Codecov"
        required: true
    inputs:
      runs-on:
        description: "The platform to run the tests on (ubuntu-latest, macos-latest, windows-latest)"
        required: true
        type: string
      python-version:
        description: "The Python version to use"
        required: true
        type: string
      setup-z3:
        description: "Whether to set up Z3"
        default: false
        type: boolean
      z3-version:
        description: "The version of Z3 to set up"
        default: "4.11.2"
        type: string

jobs:
  python-minimus:
    name: 🔧 ${{ inputs.python-version }} ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    env:
      FORCE_COLOR: 3
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: ilammy/msvc-dev-cmd@v1
      - if: ${{ inputs.setup-z3 }}
        name: Setup Z3
        uses: cda-tum/setup-z3@v1
        with:
          version: ${{ inputs.z3-version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          prepend_symlinks_to_path: false
          windows_compile_environment: msvc
          override_cache_key: python-minimus-${{ inputs.runs-on }}-${{ inputs.python-version }}
      - name: Set up mold as linker (Linux only)
        uses: rui314/setup-mold@v1
      - uses: yezz123/setup-uv@v4
      - uses: wntrblm/nox@2024.03.02
        with:
          python-versions: ${{ inputs.python-version }}
      - name: Tests with minimal versions
        run: nox -s minimums --verbose -- --cov --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          flags: python
          token: ${{ secrets.token }}
